name: Build nim-esp8266-sdk
on: push

jobs:
  build_sdk_job:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: nimesp/esp8266-gcc:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: clj/c2nim-esp8266
          path: 'c2nim-esp8266'
          submodules: true
      - run: pwd
      - run: ls
      - run: ls c2nim-esp8266


###
# when using uses: docker:// workspace is mounted in /github/workspace