name: Build nim-esp8266-sdk
on: push

jobs:
  build_sdk_job:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: nimesp/esp8266-gcc:latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: clj/nim-esp8266-sdk
          path: '.'
          submodules: true
      - uses: actions/checkout@v2
        with:
          repository: clj/c2nim-esp8266
          path: 'c2nim-esp8266'
          submodules: true
      - run: nim --version
      - run: nimble bootstrap -y
        working-directory: c2nim-esp8266
      - run: nimble build -y
        working-directory: c2nim-esp8266
      - run: make C2NIM=c2nim-esp8266/c2nim_esp8266
      - run: make C2NIM=c2nim-esp8266/c2nim_esp8266 dist
        if: ${{ startsWith(github.ref_name, 'v') }}
